repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: forbid-submodules
      - id: forbid-new-submodules
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: fix-encoding-pragma
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ --force-scope, build, ci, docs, feat, fix, perf, refactor, test, style, chore, revert ]
