app:
  env: "local"
  name: "connected_roots"
  loglevel: "debug"
api:
  protocol: "HTTP/1"
  host: "0.0.0.0"
  port: 47400
  debug: true
  recover: true
  body: "1M"
  timeouts:
    shutdown: 30
    read: 5
    write: 10
    idle: 15
  api: "4cae8c84-dd29-42f3-8d58-ed371f1bc8ef"
  health:
    frequency: 10 # (Seconds)
frontend:
  protocol: "HTTP/1"
  host: "0.0.0.0"
  port: 47500
  templates: "internal/connected_roots/frontend/web/views"
  assets: "internal/connected_roots/frontend/web/assets"
  cookie:
    name: "session"
    maxage: 86400
    key: "ZSPeYlcMLYEW1G3fWmRedM6QkSC2N8Vz6rU5GT3uDWQitRfGn9HHXstVsenPwL2Y"
    table: "sessions"
  i18n:
    path: "internal/connected_roots/frontend/i18n"
    en: "locale.en.toml"
    es: "locale.es.toml"
  debug: true
  recover: true
  body: "1M"
  timeouts:
    shutdown: 30
    read: 5
    write: 10
    idle: 15
  health:
    frequency: 10 # (Seconds)
db:
  postgres:
    dsn: "postgres://connected_roots_role:Password1@localhost:5432/connected_roots?sslmode=disable&search_path=sc_connected_roots&connect_timeout=4"
    logger:
      slowthreshold: 5
      ignorerecordnotfounderror: true
      colorful: true
    connection:
      maxidleconns: 100
      maxopenconns: 200
      connmaxidletime: 60
      connmaxlifetime: 1440
    version: 1
    health:
      frequency: 10 # (Seconds)
thirds:
    sdk:
      verbose: true
      connectedrootsservice:
        host: "http://localhost:47400"
        api: "4cae8c84-dd29-42f3-8d58-ed371f1bc8ef"
monitoring:
  observability:
    active: true
    otel:
      sdkdisabled: true
      bodydumpenabled: true
      servicename: "connected_roots"
      exporterotlpendpoint: "http://localhost:4318"
  metrics:
    active: true
    prometheus:
      disabled: false
      servicebackend: "connected_roots_backend"
      servicefrontend: "connected_roots_frontend"
      path: "/metrics"
