global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'backend'
    static_configs:
      - targets: [ 'localhost:47400' ]
  - job_name: 'frontend'
    static_configs:
      - targets: [ 'localhost:47500' ]
